apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.PolicyName }}
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        hosts: 
        {{- range .Values.hosts }}
        - {{ . | quote }}
        {{- end }}
        notPaths:
        {{- range .Values.open_access }}
        - {{ . | quote }}
        {{- end }}
  selector:
    matchLabels:
      istio: {{ .Values.gateway }}
