apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.PolicyName }}
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        hosts: 
          {{ toYaml .Values.hosts | indent 10 | quote }}
        notPaths:
          {{ toYaml .Values.open_access | indent 10 }}
  selector:
    matchLabels:
      istio: {{ .Values.gateway }}
