- name: set app fact
  set_fact:
    app: "{{ application.key }}"
    name_prefix: "namespace:{{ k8s_namespace.key }} app:{{ application.key }} -"
    application_playbook_path: "{{ local_playbook_temp }}/applications/{{ application.key }}"
  run_once: true

- block: # prepare application playbook integration
  - name: "{{ name_prefix }} clone application playbooks to Ansible Controller"
    ansible.builtin.git:
      repo: '{{ applications_git }}'
      dest: "{{ local_playbook_temp }}/applications"
      depth: 1
    ignore_errors: true
    delegate_to: localhost

  - name: "{{ name_prefix }} check for application components"
    ansible.builtin.stat:
      path: "{{ item.path }}"
    register: component_stats
    delegate_to: localhost
    loop:
      - { key: 'root', path: "{{ application_playbook_path }}" }
      - { key: 'files', path: "{{ application_playbook_path }}/files" }
      - { key: 'kustomize', path: "{{ application_playbook_path }}/kustomize" }
      - { key: 'pre_system', path: "{{ application_playbook_path }}/tasks/pre_system.yaml" }
      - { key: 'additional_images_list', path: "{{ application_playbook_path }}/vars/application_images.yaml" }
      - { key: 'additional_images_playbook', path: "{{ application_playbook_path }}/tasks/additional_images.yaml" }
      - { key: 'migrate', path: "{{ application_playbook_path }}/tasks/migrate.yaml" }
      - { key: 'post_deployment', path: "{{ application_playbook_path }}/tasks/post_deployment.yaml" }

  - name: "{{ name_prefix }} set application playbook facts"
    vars:
      results: "{{ dict(component_stats.results | map(attribute='item.key') | zip(component_stats.results)) }}"
      current_app_data:
        path: "{{ application_playbook_path }}"
        files: "{{ (results.files.stat.exists and results.files.stat.isdir) | ternary(results.files.item.path, omit) }}"
        kustomize: "{{ (results.kustomize.stat.exists and results.kustomize.stat.isdir) | ternary(results.kustomize.item.path, omit) }}"
        pre_system: "{{ (results.pre_system.stat.exists and results.pre_system.stat.isreg) | ternary(results.pre_system.item.path, omit) }}"
        additional_images_list: "{{ (results.additional_images_list.stat.exists and results.additional_images_list.stat.isreg) | ternary(results.additional_images_list.item.path, omit) }}"
        additional_images_playbook: "{{ (results.additional_images_playbook.stat.exists and results.additional_images_playbook.stat.isreg) | ternary(results.additional_images_playbook.item.path, omit) }}"
        migrate: "{{ (results.migrate.stat.exists and results.migrate.stat.isreg) | ternary(results.migrate.item.path, omit) }}"
        post_deployment: "{{ (results.post_deployment.stat.exists and results.post_deployment.stat.isreg) | ternary(results.post_deployment.item.path, omit) }}"
        vars: {}
    set_fact:
      application_playbooks: "{{ application_playbooks | default({}) | combine({application.key: current_app_data}, recursive=True) }}"
    when: results.root.stat.exists and results.root.stat.isdir
  run_once: true

- block:
  - name: "{{ name_prefix }} storage brick"
    include_tasks: common/storage_brick.yml
    loop: "{{ applications[k8s_namespace.key][application.key].storage }}"
    loop_control:
      loop_var: storage
  - name: "{{ name_prefix }} storage"
    include_tasks: common/storage.yml
    with_items: "{{ applications[k8s_namespace.key][application.key].storage }}"
    run_once: true
    loop_control:
      loop_var: storage
  - name: "{{ name_prefix }} install storage content"
    include_tasks: storage_content.yaml
    when: storage.config is defined and storage.config
    loop: "{{ applications[k8s_namespace.key][application.key].storage }}"
    loop_control:
      loop_var: storage
  when: application.value.storage is defined
  
- block:
  - name: "{{ name_prefix }} application playbook - pre_system - playbook run}}"
    include_tasks: "{{ application_playbooks[app]['pre_system'] }}"
  when: app in application_playbooks and 'pre_system' in application_playbooks[app]

