- name: set app fact
  set_fact:
    app: "{{ application.key }}"
    name_prefix: "namespace:{{ k8s_namespace.key }} app:{{ application.key }} -"
    application_playbook_path: "{{ local_playbook_temp }}/application_playbooks/{{ application.key }}"
  run_once: true

- block: # prepare application playbook integration
  - name: "{{ name_prefix }} clone application playbooks to Ansible Controller"
    ansible.builtin.git:
      repo: '{{ own_git_url }}'
      dest: "{{ local_playbook_temp }}"
      depth: 1
    ignore_errors: true
    delegate_to: localhost

  - name: "{{ name_prefix }} check if application playbook exist"
    ansible.builtin.stat:
      path: "{{ application_playbook_path }}"
    register: playbook_dir_stat
    delegate_to: localhost

  - name: "{{ name_prefix }} check if kustomize exists in application playbook"
    ansible.builtin.stat:
      path: "{{ application_playbook_path }}/kustomize"
    register: kustomize_dir_stat
    delegate_to: localhost

  - name: "{{ name_prefix }} application playbook - pre_system - playbook check"
    ansible.builtin.stat:
      path: "{{ application_playbooks[app] }}/tasks/pre_system.yaml"
    register: pre_system_stat
    delegate_to: localhost

  - name: "{{ name_prefix }} set playbook_dir_exists"
    vars:
      current_app_data:
        path: "{{ application_playbook_path }}"
        kustomize: "{{ (kustomize_dir_stat.stat.exists and kustomize_dir_stat.stat.isdir) | ternary(application_playbook_path ~ '/kustomize', omit) }}"
        pre_system: "{{ (pre_system_stat.stat.exists and pre_system_stat.stat.isfile) | ternary(application_playbook_path ~ '/tasks/pre_system.yaml', omit) }}"
    set_fact:
      application_playbooks: "{{ application_playbooks | combine({application.key: current_app_data}, recursive=True) }}"
    when: playbook_dir_stat.stat.exists and playbook_dir_stat.stat.isdir
  run_once: true


- block:
  - name: "{{ name_prefix }} application playbook - pre_system - playbook run}}"
    include_tasks: "{{ application_playbooks[app] }}/tasks/pre_system.yaml"
    when: playbook_stat.stat.exists and playbook_stat.stat.isreg
  when: app in application_playbooks and 'pre_system' in application_playbooks[app]

- block:
  - name: "{{ name_prefix }} storage brick"
    include_tasks: common/storage_brick.yml
    loop: "{{ applications[k8s_namespace.key][application.key].storage }}"
    loop_control:
      loop_var: storage
  - name: "{{ name_prefix }} storage"
    include_tasks: common/storage.yml
    with_items: "{{ applications[k8s_namespace.key][application.key].storage }}"
    run_once: true
    loop_control:
      loop_var: storage
  - name: "{{ name_prefix }} install storage content"
    include_tasks: storage_content.yaml
    when: storage.config is defined and storage.config
    loop: "{{ applications[k8s_namespace.key][application.key].storage }}"
    loop_control:
      loop_var: storage
  when: application.value.storage is defined
  
