- name: set app fact
  set_fact:
    app: "{{ application.key }}"
    name_prefix: "namespace:{{ k8s_namespace.key }} app:{{ application.key }} -"
    application_playbook_path: "{{ local_playbook_temp }}/application_playbooks/{{ application.key }}"
  run_once: true

- block: # prepare application playbook integration
  - name: "{{ name_prefix }} clone application playbooks to Ansible Controller"
    ansible.builtin.git:
      repo: '{{ own_git_url }}'
      dest: "{{ local_playbook_temp }}"
      depth: 1
    ignore_errors: true
    delegate_to: localhost

  - name: "{{ name_prefix }} check if application playbooks exist"
    ansible.builtin.stat:
      path: "{{ application_playbook_path }}"
    register: playbook_dir_stat
    delegate_to: localhost

  - name: "{{ name_prefix }} set playbook_dir_exists"
    set_fact:
      application_playbooks: "{{ application_playbooks | combine({application.key: application_playbook_path }, recursive=True) }}"
      #playbook_dir_exists: "{{ playbook_dir_stat.stat.exists if (playbook_dir_stat.stat.exists and playbook_dir_stat.stat.isdir) else false }}"
      #playbook_path: "{{ local_playbook_temp }}/application_playbooks/{{ application.key }}"
    when: playbook_dir_stat.stat.exists and playbook_dir_stat.stat.isdir
  run_once: true


- block:
  - name: "{{ name_prefix }} application playbook - pre_system - playbook check"
    ansible.builtin.stat:
      path: "{{ application_playbooks[app] }}/pre_system.yaml"
    register: playbook_stat
    delegate_to: localhost

  - name: "{{ name_prefix }} application playbook - pre_system - playbook run}}"
    include_tasks: "{{ application_playbooks[app] }}/pre_system.yaml"
    when: playbook_stat.stat.exists and playbook_stat.stat.isreg
  when: app in application_playbooks

- block:
  - name: "{{ name_prefix }} storage brick"
    include_tasks: common/storage_brick.yml
    loop: "{{ applications[k8s_namespace.key][application.key].storage }}"
    loop_control:
      loop_var: storage
  - name: "{{ name_prefix }} storage"
    include_tasks: common/storage.yml
    with_items: "{{ applications[k8s_namespace.key][application.key].storage }}"
    run_once: true
    loop_control:
      loop_var: storage
  - name: "{{ name_prefix }} install storage content"
    include_tasks: storage_content.yaml
    when: storage.config is defined and storage.config
    with_items: "{{ applications[k8s_namespace.key][application.key].storage }}"
    loop_control:
      loop_var: storage
  when: application.value.storage is defined
  
