- set_fact:
    # dest_base_dir: "{% if storage.type == 'local_folder' %}{{ local_disk_directory }}{% else %}{{ shared_mounts }}{% endif %}/{{ storage.name }}"
    dest_hosts: "{% if storage.type == 'local_folder' %}{{ hostvars.keys() }}{% else %}{{ [hostvars.keys() | first] }}{% endif %}"
  run_once: true

- block:
  - name: deploy templates
    include_role:
      name: shared_helper
      tasks_from: template_directory.yaml
    vars:
      destination_dir: "{{ storage.dest_dir }}/"
      template_source_dir: "{{ application_playbooks[application.key] }}/templates"
      owner: "{{ application.value.security.runAsUser }}"
      group: "{{ application.value.security.runAsGroup }}"
      directoryMode: "{{ application.value.security.directoryMode }}"
      fileMode: "{{ application.value.security.fileMode }}"

  - block:
    - name: deploy from files
      synchronize:
        src: "{{ application_playbooks[application.key]['files'] }}"
        dest: "{{ storage.dest_dir }}/"
        rsync_opts:
        - "--relative"
        - "--copy-links"

    - name: set ownership
      file:
        path: "{{ storage.dest_dir }}"
        recurse: true
        owner: "{{ application.value.security.runAsUser }}"
        group: "{{ application.value.security.runAsGroup }}"
    when: application.key in application_playbooks and 'files' in application_playbooks[application.key]
  when: inventory_hostname in dest_hosts

