- block:
  # -name: check if root ca exists and is valid
  - name: certificates
    vars:
      certificates_configuration: "{{ my_certs.conf }}"
      ca_init: false
      ca_requests:
      - name: {{ registry_host }}
        alt_names: 
        - {{ registry_host }}
      - name: my-lb.adm13
        alt_names:
        - my-lb.adm13
        - '*.my-lb.adm13'
        - adm13.dnshome.de
      - name: ha.my-lb.adm13
        alt_names:
        - ha.my-lb.adm13
        - adm13.dnshome.de
    include_role: 
      name: certificates
  run_once: true

