apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
data:
  initconfig.sh: |
    #!/bin/sh
    
    cd /app
    node index.js
