apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ kustom.name }}
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ kustom.name }}
          restartPolicy: OnFailure
          containers:
          - name: checker
            image: {{ kustom.image }}
            command:
            - /bin/sh
            - -c
            - |
              # 1. Check if the registry is up (returns 200)
              # Replace with your actual registry health endpoint
              set -x
              STATUS=$(curl --cacert /etc/certs/service-ca-bundle.crt -o /dev/null -s -w "%{http_code}" https://{{ registry }}/v2/)
              
              if [ "$STATUS" -eq 200 ]; then
                VAL="available"
              else
                VAL="unavailable"
              fi

              echo "Registry status is $VAL ($STATUS). Updating ConfigMap..."

              APISERVER="https://kubernetes.default.svc"
              SERVICEACCOUNT="/var/run/secrets/kubernetes.io/serviceaccount"
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
              TOKEN=$(cat ${SERVICEACCOUNT}/token)
              CACERT=${SERVICEACCOUNT}/ca.crt

              # patch the configmap
              curl --cacert "${CACERT}" -X PATCH -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/merge-patch+json" \
                   --data "{\"data\":{\"registry\":\"{\\\"state\\\": \\\"$VAL\\\"}\"}}" "${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/{{ kustom.name }}"
            volumeMounts:
            - name: {{ kustom.name }}-certs
              mountPath: /etc/certs
              readOnly: true
          volumes:
          - name: {{ kustom.name }}-certs
            configMap:
              name: {{ kustom.name }}-certs
