namespace: {{ kustom.namespace }}

resources:
- CronJob.yaml
- RoleBinding.yaml
- Role.yaml
- ServiceAccount.yaml

configMapGenerator:
- name: {{ kustom.name }}
  literals: []
- name: {{ kustom.name }}-certs
  literals:
  - |
    service-ca-bundle.crt={{ application_playbooks[application.key].vars.ca_bundle | indent(4) }}

generatorOptions:
  disableNameSuffixHash: true
