roles:
- src: git+https://github.com/cainam/gentoo-image-builder.git
  version: main
  name: gentoo-image-builder

#- name: shared_helper
#  src: git+https://github.com/cainam/ansible_helper_playbooks.git
#  scm: git
#  version: main

collections:
  - name: git+https://github.com/cainam/ansible_helper_playbooks.git
    type: git
    version: main

#- src: git+https://github.com/robertdebock/ansible-role-ca.git
#  version: master
#  name: certificates
