---
# file: site.yml
- hosts: all
  gather_facts: no
  any_errors_fatal: true
  vars:
    auto_legacy_silent: true
    auto_silent: true
    ansible_python_interpreter: /usr/bin/python # to avoid interpreter warning
    kubeconfig: /etc/kubernetes/admin.conf
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
    PATH: "{{ path }}"
    registry: "{{ registry }}"
  pre_tasks:
  - name: load configuration
    include_vars: "{{ item }}"
    tags:
    - deploy
    - k8s
    - testing
    - gentoo
    - images-only
    loop:
    - vars/build-images.yaml
    - vars/software
    - vars/images
    run_once: true
  - name: setup # to gather facts only when needed
    setup:
    tags:
    - gentoo
    - k8s
  roles:
    - role: always
      tags:
        - always
    - role: k8s
      tags: 
        - never
        - k8s
    - role: gentoo
      tags: 
        - never
        - gentoo
    - role: deploy
      tags:
        - never
        - deploy
    - role: raspberry
      tags:
        - never
        - raspberry
    - role: certs-only
      tags:
        - never
        - certs-only
  tasks:
    - block:
        - name: import role
          import_role:
            name: images-only
      vars: 
        image_builder_node: "{{ groups['all'] | map('extract', hostvars) | selectattr('system_roles', 'defined') | selectattr('system_roles', 'contains', 'image_builder') | map(attribute='inventory_hostname') | first }}"
      tags:
        - never
        - images-only
