---
- name: get seed
  shell: echo $RANDOM
  run_once: true
  register: seed
  
- set_fact:
    selected_host: "{{ ansible_play_hosts | random(seed=seed.stdout) }}"

- debug: 
    msg: "selected_host:{{ selected_host }}"


- name: system configurations
  import_tasks: system.yml

- name: install kubernetes
  import_tasks: install_k8s.yml

# update if version is newer 
- name: get k8s version
  shell: "grep image: {{ k8s_check_file }} | cut -d : -f 4"
  register: current_k8s_version
  
- debug:
    msg: "installed k8s version: {{ current_k8s_version }}"
  
- debug: 
    msg: update
  when: current_k8s_version.stdout is version( k8s_version, '<')
- name: update k8s
  shell: "kubeadm upgrade apply {{ k8s_version }}"
  when: current_k8s_version.stdout is version( k8s_version, '<')
