---
- name: get seed
  shell: echo $RANDOM
  run_once: true
  register: seed
  
- set_fact:
    selected_host: "{{ ansible_play_hosts | random(seed=seed.stdout) }}"

- debug: 
    msg: "selected_host:{{ selected_host }}"


- name: system configurations
  import_tasks: system.yml

- name: install kubernetes
  import_tasks: install_k8s.yml

# update if version is newer 
- name: get k8s version
  shell: "grep image: {{ k8s_check_file }} | cut -d : -f 4"
  register: current_k8s_version
  
- debug:
    msg: "installed k8s version: {{ current_k8s_version }}"
  
- debug: 
    msg: update
  when: current_k8s_version.stdout is version( k8s_version, '<')
- name: update k8s
  shell: "kubeadm upgrade apply --yes {{ k8s_version }}"
  when: current_k8s_version.stdout is version( k8s_version, '<')

- name: ca template
  template:
    src: ca
    dest: /tmp/myca

- name: create CA configmap
  shell: |
    kubectl apply -f /tmp/myca

- name: additional DNS entries
  shell: |
    kubectl get -o yaml cm coredns -n kube-system  | sed -e '/hosts/,/}/d'| sed -e 's/^\(\s*\)\(errors\)\s*$/\1\2\n\1hosts {\n\1  192.168.4.100 my-lb.adm13\n\1}/g' | kubectl replace -f -
