---
- name: hostname
  shell: hostname
  register: hn
  changed_when: false

- debug: 
    msg: "selected_host: {{ selected_host }}, real hostname: {{ hn.stdout }}"

- name: get list of images
  shell: kubeadm config images list 2>/dev/null
  register: required_images

- debug:
    msg: "images to download: {{ required_images.stdout_lines }}"

- name: pull, tag and push k8s images
  shell: |
    podman pull {{ item }} ;
    loc_img=myregistry.adm13:443/$(echo "{{ item }}" | xargs basename);
    podman tag "{{ item }}" "$loc_img";
    podman push "$loc_img";
  with_items: "{{ required_images.stdout_lines }}"

