---
- name: hostname
  shell: hostname
  register: hn
  changed_when: false

- debug: 
    msg: "selected_host: {{ selected_host }}, real hostname: {{ hn.stdout }}"

- name: get list of images
  shell: kubeadm config images list --kubernetes-version "{{ k8s_version }}" 2>/dev/null
  register: required_images
  changed_when: false

- debug:
    msg: "images to download: {{ required_images.stdout_lines }}"

- name: check if container registry is available
  shell: curl -s -X GET https://{{ my_registry }}/v2/_catalog | jq 'has("repositories")'
  register: check_registry
  
- name: restart registry
  shell: /etc/init.d/registry restart
  when: check_registry.stdout != "true"

- name: pull, tag and push k8s images
  shell: |
    echo "arm64 {{ item }} /k8s/ # required for kubernetes" | bash pull-tag-push.sh
  with_items: "{{ required_images.stdout_lines }}"

- name: prepare flannel
  shell: |
    # curl -O https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    # grep image kube-flannel.yml | grep -v "#image" | awk '{print $2}' | sed -e 's/^/arm /g' -e 's#$# /k8s/ images for kube-flannel#g' | bash pull-tag-push.sh
    . set_env.sh kube-flannel
    helm:from_git_to_local.sh --platform=arm64 --git_source=https://github.com/flannel-io/flannel.git --git_subdir=chart/kube-flannel --chart_version= --appVersion= --remove_dependencies=
    helm repo add kube-flannel https://helm.adm13:9443/kube-flannel
    helm repo index "${helm_repo_dir}" --url $helm_url

