---
- name: rc.conf
  lineinfile:
    path: /etc/rc.conf
    regexp: "^{{ item.setting }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.setting }}"
    backup: yes
  loop:
    - line: 'rc_cgroup_mode="legacy"'
      setting: rc_cgroup_mode
    - line: 'rc_cgroup_controllers=""'
      setting: rc_cgroup_controllers

#- name: mount boot
#  shell: mount /boot || true
#  changed_when: false 
#   
#- name: cmdline
#  lineinfile:
#    path: /boot/cmdline.txt
#    state: present
#    create: true
#    regexp: '^((?!.*{{ item }}).*console.*)$'
#    line: '\1 {{ item }}'
#    backrefs: yes
#  loop:
#    - cgroup_enable=memory
#    - cgroup_memory=1
#    - cgroup_enable=cpuset
#    - swapaccount=1
#    - ipv6.disable=1
#    - firmware_class.path=/linux-firmware/updates

- name: deploy configuration files
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  loop:
    - etc/sysctl.d/k8s.conf
    - etc/modules-load.d/k8s.conf
    - etc/conf.d/kubelet

- name: enable kubelet service
  service:
    name: kubelet
    enabled: yes

- name: check /var/lib/etcd
  stat:
    path: "/var/lib/etcd"
  register: etcd_data

- name: ensure /data/etcd exists
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.perm }}"
  loop:
    - path: /data/etcd
      perm: u=rwx,g=rx,o=rx

- name: ensure /var/lib/etcd is absent
  file:
    path: /var/lib/etcd
    state: absent
  when: not ( etcd_data.stat.islnk is defined and etcd_data.stat.islnk)

- name: create /var/lib/etcd link to /data/etcd
  file:
    src: "/data/etcd"
    dest: "/var/lib/etcd"
    owner: root
    group: root
    state: link
  when: not ( etcd_data.stat.islnk is defined and etcd_data.stat.islnk)

