- name: emerge sync
  shell: emerge --sync
  ignore_errors: true

- name: portage profile
  shell: export LC_ALL=C && eselect profile show && eselect profile set default/linux/arm64/23.0

- set_fact:
    gpg_dir: /etc/portage/gpg

- name: ensure required directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.perm|default('0700') }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.owner|default('root') }}"
  loop:
  - path: "{{ gpg_dir }}"
  - path: /var/lib/portage/binpkg-verify
    owner: nobody

- block:
  - name: check if valid signing key exists
    shell: >
      gpg --homedir {{ gpg_dir }} --with-colons --list-keys awk -F: '($1=="pub" || $1=="sub") && $2 !~ /[red]/ && $12 ~ /s/ {print $5}'
    register: signing_key
    changed_when: false
    failed_when: false
    run_once: true

  - name: create valid signing key
      shell: gpg --homedir {{ gpg_dir }} --batch --passphrase '' --quick-gen-key "Cainam Gentoo Binhost Signer <root@gentoo-binhost>" rsa4096 default 2y
    when: signing_key.stdout_lines | length == 0
    run_once: true

  - name: export signing key
    shell: >
      k=$(gpg --homedir {{ gpg_dir }} --with-colons --fingerprint | grep ^fpr | cut -d : -f 10 | tail -n 1)
      gpg --homedir {{ gpg_dir }} --export "$k"
    register: signing_key
    changed_when: false
    run_once: true
  delegate_to: "{{ gentoo_builder }}"

- name: set-up signing verification
  shell: |
    k=$(echo "{{ signing_key }}" | gpg --show-keys --with-colons --fingerprint | grep ^fpr | cut -d : -f 10 | tail -n 1)
    echo "{{ signing_key }}" | su -s /bin/sh nobody -c 'GNUPGHOME=/var/lib/portage/binpkg-verify  gpg --import'
    echo "$k" > /tmp/k
    echo "{{ signing_key }}" >  /tmp/s
    printf '%s:6:\n' "$k" | su -s /bin/sh nobody -c 'GNUPGHOME=/var/lib/portage/binpkg-verify gpg --import-ownertrust'
    su -s /bin/sh nobody -c 'GNUPGHOME=/var/lib/portage/binpkg-verify gpg --check-trustdb'

- name: build and deploy
  block:
  - name: park /boot/cmdline.txt and /boot/config.txt to enable sys-boot/raspberrypi-firmware installation (breaks for hard check in ebuild)
    shell: test -f "{{ item }}" && mv "{{ item }}" "{{ item }}.deployed"
    loop:
    - /boot/cmdline.txt
    - /boot/config.txt

  - name: emerge build
    shell: emerge --keep-going --verbose --update --deep --newuse --with-bdeps=y @world
    when: alt_names is defined and alt_names.gentoo_build is defined and 'emerge' in ansible_run_tags

  - name: link check_and_fix.sh cron
    file:
      src: /usr/local/bin/check_and_fix.sh
      dest: /etc/cron.hourly/check_and_fix.sh
      state: link

  - name: emerge deploy
    shell: emerge --keep-going --verbose --update --deep --newuse --with-bdeps=y @world
    when: (alt_names is not defined or (alt_names is defined and alt_names.gentoo_build is not defined)) and 'emerge' in ansible_run_tags

  always:
  - name: un-park /boot/cmdline.txt and /boot/config.txt to enable sys-boot/raspberrypi-firmware installation (breaks for hard check in ebuild)
    shell: test -f "{{ item }}.deployed" && mv "{{ item }}.deployed" "{{ item }}"
    loop:
    - /boot/cmdline.txt
    - /boot/config.txt

- name: eclean distfiles
  shell: eclean distfiles
  when: alt_names is defined and alt_names.gentoo_build is defined and 'emerge' in ansible_run_tags

- name: eclean packages
  shell: eclean packages

- name: emerge depclean
  shell: emerge --depclean

- name: emerge preserved rebuild
  shell: emerge @preserved-rebuild
  when: alt_names is defined and alt_names.gentoo_build is defined and 'emerge' in ansible_run_tags

- name: emerge preserved rebuild
  shell: emerge @preserved-rebuild
  when: alt_names is defined and alt_names.gentoo_build is not defined and 'emerge' in ansible_run_tags
