---
- name: set gentoo_builder variable
  set_fact:
    gentoo_builder: "{{ groups['all'] | map('extract', hostvars) | selectattr('alt_names.gentoo_build', 'defined') | map(attribute='inventory_hostname') | first | mandatory }}"

- name: create user podman
  user:
    name: podman
    shell: /bin/nologin
    group: nogroup
    home: /home/podman
    uid: 9823907

- name: ensure required directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.perm|default('u=rwx,g=rx,o=rx') }}"
    owner: "{{ item.owner|default('root') }}"
  loop:
    - path: /etc/modprobe.d
    - path: /etc/wpa_supplicant
    - path: "{{ shared_mounts }}"
    - path: /etc/modules-load.d
    - path: /usr/local/share/ca-certificates/
    - path: "{{ gluster_directory }}/bricks"
    - path: /etc/autofs
    - path: /var/lib/iwd
    - path: /etc/iwd
    - path: /etc/cron.hourly
      perm: u=rwx,g=rx
    - path: ~podman/.ssh
      perm: u=rwx,g=,o=
      owner: podman

- name: auto.master
  lineinfile: 
    path: /etc/autofs/auto.master
    regexp: "^{{ shared_mounts }}"
    line: "{{ shared_mounts }} /etc/autofs/gluster.autofs"
    backup: yes
    create: true

- block:
  - name: "certificates"
    vars:
      cert_results_var: "my_cert"
      caBundle_var: "caBundle"
      ca_init: true
      certificates_configuration: "{{ my_certs.conf }}"
      ca_requests: "{{ my_certs.certs }}"
    include_role:
      name: certificates
  delegate_to: localhost
  run_once: true

- name: copy root and intermediate CA
  copy:
    src: "{{ cert_path }}/{{ item }}"
    dest: "{{ system_local_certs }}/{{ item }}"
    owner: root
    group: root
  register: ca
  loop: "{{ my_certs.local_ca_files }}"

- name: update CA certificates
  shell: /usr/sbin/update-ca-certificates
  when: ca.changed

- name: put certificate keys in place
  copy:
    src: "{{ cert_path }}/{{ my_certs.conf.ca_common_name }}/subject_keys/{{ item.name }}.pem"
    dest: "{{ item.dest }}/{{ item.name }}.key"
  loop: "{{ my_certs.certs }}"

- name: put certificates in place
  copy:
    src: "{{ cert_path }}/{{ my_certs.conf.ca_common_name }}/certs/{{ item.name }}.crt"
    dest: "{{ item.dest }}/{{ item.name }}.crt"
  loop: "{{ my_certs.certs }}"

- name: rc.conf
  lineinfile:
    path: /etc/rc.conf
    regexp: "^{{ item.setting }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.setting }}"
    backup: yes
  loop:
    - line: 'rc_logger="YES" # write rc logs to /var/log/rc.log, otherwise boot logs are lost'
      setting: rc_logger
    - line: 'rc_verbose="yes" # be verbose'
      setting: rc_verbose

- name: hostname in /etc/conf.d
  copy:
    content: hostname="{{ inventory_hostname }}"
    dest: /etc/conf.d/hostname

- name: first line in iwd security file
  lineinfile:
    path: /var/lib/iwd/AdM13.psk
    insertbefore: BOF
    create: true
    line: "[Security]"

- name: passphrase for iwd
  lineinfile:
    path: /var/lib/iwd/AdM13.psk
    regexp: '^Passphrase='
    line: "Passphrase={{ psk }}"

- name: PreSharedKey for iwd
  lineinfile:
    path: /var/lib/iwd/AdM13.psk
    regexp: '^PreSharedKey='
    line: "PreSharedKey={{ PreSharedKey }}"

- name: /etc/ssh/known_hosts
  copy:
    content: |
      {% for i in ssh_keys.hosts %}
      {{i~' ssh-'~ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].public}}
      {{(i| split('.') | first)~' ssh-'~ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].public}}
      {% if hostvars[i].alt_names is defined %}
      {% for j in hostvars[i].alt_names %}
      {{j~' ssh-'~ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].public}}
      {% endfor %}
      {% endif %}
      {% endfor %}   
    dest: /etc/ssh/ssh_known_hosts

- name: ssh keys
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('u=rw,g=r,o=r') }}"
  loop:
  - content: "ssh-{{ ssh_keys.hosts[inventory_hostname].type~' '~ssh_keys.hosts[inventory_hostname].public~' root@'~inventory_hostname }}"
    dest: /etc/ssh/ssh_host_{{ ssh_keys.hosts[inventory_hostname].type }}_key.pub
  - content: "{{ ssh_keys.hosts[inventory_hostname].private}}"
    dest: /etc/ssh/ssh_host_{{ ssh_keys.hosts[inventory_hostname].type }}_key
    mode: u=rw,g=,o=
  - content: "ssh-{{ ssh_keys.hosts[inventory_hostname].type~' '~ssh_keys.hosts[inventory_hostname].admin_pub~' root@'~inventory_hostname }}"
    dest: /root/.ssh/id_{{ ssh_keys.hosts[inventory_hostname].type }}.pub
  - content: "{{ ssh_keys.hosts[inventory_hostname].admin_key }}"
    dest: /root/.ssh/id_{{ ssh_keys.hosts[inventory_hostname].type }}
    mode: u=rw,g=,o=
  - content: "{{ ssh_keys.podman.key }}"
    dest: "~podman/.ssh/id_ed25519"
    owner: podman
    group: nogroup
    mode: u=rw,g=,o=
  - content: "{{ ssh_keys.podman.pub }}"
    dest: "~podman/.ssh/id_ed25519.pub"
    owner: podman
    group: nogroup
  - content: "{{ ssh_keys.podman.pub }}"
    dest: "~podman/.ssh/authorized_keys"
    owner: podman
    group: nogroup

- name: authorized_keys
  copy:
    content: |
      {% for i in ssh_keys.hosts %}
      ssh-{{ ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].admin_pub~' root@'~i }}
      {% endfor %}
      {% if ssh_keys.remote_admin is defined %}
      {% for j in ssh_keys.remote_admin %}
      {{ j }}
      {% endfor %}
      {% endif %}
    dest: /root/.ssh/authorized_keys

- name: test if ssh CA exists
  ansible.builtin.stat:
    path: "{{ cert_path }}/ssh_ca"
  register: ssh_ca
  delegate_to: localhost

- name: create ssh CA
  shell: ssh-keygen -t ed25519 -f "{{ cert_path }}/ssh_ca" -C "SSH-Cluster-CA"
  delegate_to: localhost
  run_once: true
  when: not ssh_ca.stat.exists

- name: read ssh public host key
  ansible.builtin.slurp:
    src: /etc/ssh/ssh_host_ed25519_key.pub
  register: public_host_key
  run_once: true

- name: place public host key for signing
  ansible.builtin.copy:
    dest: "{{ cert_path }}/ssh_host_ed25519_key_{{ inventory_hostname }}.pub"
    content: "{{ public_host_key['content'] | b64decode }}"
  delegate_to: localhost
  
- name: sign public host keys
  ansible.builtin.shell: >
    ssh-keygen -s "{{ cert_path }}/ssh_ca" -I "host_{{ inventory_hostname }}" -h -V +52w 
    -n "{{ inventory_hostname }},{% for l in net.virtual_ips %}{{ l.ip }}{% for n in l.names %},{{ n }}{%endfor %}{% endfor %}" "{{ cert_path }}/ssh_host_ed25519_key_{{ inventory_hostname }}.pub"
  delegate_to: localhost

- name: read the signed certificate back
  ansible.builtin.slurp:
    src: "{{ cert_path }}/ssh_host_ed25519_key_{{ inventory_hostname }}-cert.pub"
  register: signed_cert
  delegate_to: localhost

- name: write the signed certificate to node
  ansible.builtin.copy:
    dest: /etc/ssh/ssh_host_ed25519_key-cert.pub
    content: "{{ signed_cert['content'] | b64decode }}"
    owner: root
    group: root
    mode: '0644'

- name: deploy from files
  synchronize:
    src: "{{ role_path }}/files/./"
    dest: "/"
    archive: yes
    recursive: yes
    rsync_opts:
      - "--relative"

- name: set my role_path
  set_fact:
    my_role_path: "{{ role_path }}"

- name: deploy etc from templates
  include_role:
    name: shared_helper
    tasks_from: template_directory.yaml
  vars:
    destination_dir: "/etc"
    template_source_dir: "{{ my_role_path }}/templates/etc"
    data_uuid: '{{ ansible_facts.mounts | selectattr("mount","==","/data") | map(attribute="uuid") | first | default(None) }}'

- name: ensure all filesystems are mounted
  shell: mount -a && (grep /boot /etc/fstab | grep -v ^# |  awk '{print $2}' | xargs mount)
  changed_when: false 

- name: deploy from templates to /boot
  template:
    src: "{{ item.file }}"
    dest: /boot/
    backup: no
  loop:
  - file: cmdline.txt
  - file: config.txt

- name: symlinks for net.lo, iptables, localtime
  file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    owner: root
    group: root
    state: link
    force: true
  loop:
    - src: net.lo
      path: /etc/init.d/net.end0
    - src: "/usr/share/zoneinfo/{{ timezone }}"
      path: /etc/localtime
    - src: xtables-nft-multi
      path: /usr/bin/iptables
    - src: xtables-nft-multi
      path: /usr/bin/iptables-restore
    - src: xtables-nft-multi
      path: /usr/bin/iptables-save
    - src: ip6tables-nft
      path: /usr/bin/ip6tables
    - src: ip6tables-nft
      path: /usr/bin/ip6tables-restore
    - src: ip6tables-nft
      path: /usr/bin/ip6tables-save

- name: cron - purge.sh
  file:
    src: /usr/local/bin/purge.sh
    dest: /etc/cron.daily/purge.sh
    state: link

- name: manage deploy gentoo cron link
  file:
    src: "{{ '/usr/local/bin/deploy_gentoo.sh' if (alt_names is defined and alt_names.gentoo_build is defined) else omit }}"
    dest: /etc/cron.daily/deploy_gentoo.sh
    state: "{{ 'link' if (alt_names is defined and alt_names.gentoo_build is defined) else 'absent' }}"

- name: set date if year is 1970
  shell: date +%Y | ( grep -q "^1970$" && date -s "{{ now(fmt='%Y-%m-%d %H:%M:%S') }}" ) || echo "date ok"

- name: get hostname of Ansible control node
  connection: local
  run_once: true
  delegate_to: localhost
  set_fact:
    ansible_controller_hostname: "{{ lookup('pipe', 'hostname') }}"

- name: emerge
  import_tasks: emerge.yaml

- name: install additional modules from Ansible Galaxy
  shell: ansible-galaxy collection install gluster.gluster --upgrade #--collections-path /usr/lib/python3.12/site-packages/ansible_collections
  failed_when: false

#- name: disable services
#  service:
#    name: "{{ item }}"
#    enabled: no
#    state: stopped
#  loop:

- name: enable keepalive only on control_plane nodes 
  service:
    name: "{{ item }}"
    enabled: yes
    state: reloaded
  loop:
    - keepalived
  when: inventory_hostname in (groups['all'] | map('extract', hostvars) | selectattr('system_roles', 'defined') | selectattr('system_roles', 'contains', 'control_plane') | map(attribute='inventory_hostname') )

- name: enable and restart services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - net.end0
    - chronyd
    - brickmount
    - glusterd
    - cronie
    - cpupower
    - iwd
    - sysctl
  ignore_errors: yes

- name: only enable and reload services, but don't force a restart
  service:
    name: "{{ item }}"
    enabled: yes
    state: reloaded
  loop:
    - autofs
    - sshd
    - haproxy
    - crio
    - syslog-ng
    - conntrackd
    - iscsid

- name: gluster
  import_tasks: gluster.yaml
