- block:
  - name: get list of images
    shell: |
      for img in $(kubeadm config images list --kubernetes-version {{ k8s_version }} | grep -v etcd ); do
        repo_and_tag="${img##*/}" # strip registry and path (everything before the last /)
        # Extract the image name and the tag
        image="${repo_and_tag%:*}"
        tag="${repo_and_tag##*:}"
        echo "$image: $tag"
      done
    register: required_images_raw
    changed_when: false

  - name: Set images as an Ansible dictionary
    set_fact:
      required_images_dict: "{{ required_images_raw.stdout | from_yaml }}"

  - name: generate the images structure for the builder
    set_fact:
      required_images: >-
        {{
          required_images | default([]) + [{
            'name': item.key,
            'tag': item.value,
            'section': kubernetes_image_section,
            'type': 'fetch',
            'source': 'registry.k8s.io/' ~ item.key
          }]
        }}
    loop: "{{ required_images_dict | dict2items }}"

  - name: load image information as yaml
    set_fact:
      images: "{{ images + required_images + k8s_images }}"
      image_names: "{{ ['registry','flannel','flannel-cni-plugin'] + (required_images | map(attribute='name')) + (k8s_images | map(attribute='name')) }}"
  run_once: true
  delegate_to: "{{ selected_host }}"

- name: handle additional images
  vars:
    limit_images: "{{ image_names }}"
    dry_run: false
  include_role:
    name: gentoo-image-builder

