FROM scratch
LABEL maintainer Your Name <your@mail.org>

ADD rootfs.tar /

#COPY docker-healthcheck.sh /usr/bin/docker-healthcheck
#HEALTHCHECK --interval=60s --timeout=5s --start-period=5s --retries=3 CMD ["docker-healthcheck"]

#CMD ["/bin/some-cmd", "--some-option", "some-value"]

LABEL kubler.build.timestamp=20250220215025
