---
- name: test
  gather_facts: false
  hosts: all

  tasks:
  # Get cert info
  - name: set title
    set_fact:
      title: "this is title"

  - name: "{{ title }}"
    debug:
      msg: 'title: {{ title }}'

