---

- name: test 
  gather_facts: false
  hosts: all

  tasks:
  - block:
    - debug: 
        msg: "now: {{ now(fmt='%Y-%m-%d %H:%M:%S') }}"
    - set_fact:
        var_omit: "{{ b | default(omit) }}"
        ivar_omit: "lkj"

    - debug: 
        msg: "var_omit: {{ var_omit }}"
    run_once: true

