apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idp.fullname" . }}
  labels:
{{ include "idp.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  data:
    username: {{ .Values.username }}
    password: {{ .Values.password }}
  selector:
    app.kubernetes.io/name: {{ include "idp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
