apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idp.fullname" . }}
  labels:
{{ include "idp.labels" . | indent 4 }}
type: Opaque
spec:
  data:
    username: {{ .Values.username | b64enc }}
    password: {{ .Values.password | b64enc }}
  selector:
    app.kubernetes.io/name: {{ include "idp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
