---
- name: update postgresql major release
  gather_facts: false
  hosts: all
  vars:
    upgrade_job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: pg-upgrade
        namespace: db
        labels:
          app: pg-upgrade
      spec:
        ttlSecondsAfterFinished: 1000
        template:
          spec:
            volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-postgresql-0
            containers:
            - name: upgrade-postgresql
              image: db/pg_upgrade
              command: ["/pg_upgrade.sh"]
              volumeMounts:
              - name: data
                mountPath: /data
            restartPolicy: Never
        backoffLimit: 4

  tasks:
  - block:
    - name: scale down postgresql 
      shell: |
        . set_env.sh
        kubectl scale --replicas=0 -n db statefulset postgresql

    - name: delete old job
      shell: |
        . set_env.sh
        kubectl delete job -n db pg-upgrade
      failed_when: false

    - name: run upgrade job
      shell: |
        . set_env.sh
        echo "{{ upgrade_job }}" | kubectl apply -f - 

    # add a conition her to wait until job is finished
    - name: scale down postgresql 
      shell: |
        . set_env.sh
        kubectl scale --replicas=1 -n db statefulset postgresql
      when: false
      
    run_once: true
