- debug:
    msg: "{{ applications[k8s_namespace.key][application.key] }}"
- debug:
    msg: "{{ applications[k8s_namespace.key][application.key].storage }}"
- debug:
    msg: "{{ applications[k8s_namespace.key][application.key].storage | first }}"

- name: software configuration file
  copy:
    content: "{{ software | to_nice_yaml }}"
    dest: "{{ (applications[k8s_namespace.key][application.key].storage | first) | map(attribute='dest_dir') }}"
