---
applications:
  istio-system:
    base: 
      git: https://github.com/istio/istio.git
      platform: arm
      subdir: manifests/charts/base
    istiod: 
      git: https://github.com/istio/istio.git
      platform: arm
      subdir: manifests/charts/istio-control/istio-discovery
      helm_options: --set global.proxy.privileged=true --set pilot.image=istio/pilot:1.16.2 --set global.proxy.image=istio/proxyv2:1.16.2 --set global.proxy_init.image=istio/proxyv2:1.16.2 --set global.tracing.zipkin.address=jaeger-collector.tools:9411 --set pilot.resources.requests.memory=128Mi
  istio-ingress:
    gateway:
      git: https://github.com/istio/istio.git
      subdir: manifests/charts/gateway
      helm_options: --set 'service.externalIPs={"{{ load_balancer_ip }}"}' 
  auth:
    oauth2-proxy:
      git: https://github.com/oauth2-proxy/manifests.git
      subdir: helm/oauth2-proxy
      helm_options: --set proxyVarsAsSecrets=false \{% if application is defined %\}\{% if application.value.files.config.tempfile is defined %\}--values \{\{ application.value.files.config.tempfile \}\} \{% endif %\}\{% endif %\}
      files:
        config:
          file: oauth2-proxy-config.yaml
      network:
        gwPort: 2004
        targetPort: 12004
        svcPort: 80
    keycloak:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: keycloak
      helm_options: --set securityContext.runAsUser=100200 --set server.securityContext.fsGroup=100200
      storage:
      - name: keycloak
        size: 1Gi
      network:
        gwPort: 2005
        targetPort: 12005
        svcPort: 1121
  tools:
    jaeger:
      git: https://github.com/jaegertracing/helm-charts.git
      subdir: charts/jaeger
      remove_dependencies: kafka,elasticsearch
      helm_options: --set provisionDataStore.cassandra=false --set allInOne.enabled=true --set storage.type=none --set agent.enabled=false --set collector.enabled=false --set query.enabled=false --set allInOne.args[0]="--query.base-path=/jaeger"
      network:
        svcName: jaeger-query
        rewrite: /jaeger
        svcPort: 16686
    infopage:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: infopage
      storage:
      - name: infopage
        size: 5Mi
      network:
        xsvcPort: 1111
    kiali-operator:
      git: https://github.com/kiali/helm-charts.git
      subdir: kiali-operator 
      chart_version: v1.62.0
      appVersion: v1.62.0
      helm_options:  --set cr.create=true --set cr.spec.auth.strategy=anonymous --set cr.namespace=tools --set cr.spec.istio_namespace=istio-system --set image.repo=myregistry.adm13:443/tools/kiali-operator --set image.tag=v1.62.0 --set allowAdHocKialiImage=true --set cr.spec.deployment.image_name=myregistry.adm13:443/tools/kiali --set cr.spec.deployment.image_version=v1.62.0 --set cr.spec.external_services.prometheus.url="http://prometheus-server.tools/" --set cr.spec.external_services.prometheus.auth.insecure_skip_verify=true
      network:
        svcPort: 20001
        svcName: kiali
        prefix: /kiali
        rewrite: /kiali
    kubernetes-dashboard:
      git: https://github.com/kubernetes/dashboard.git
      subdir: charts/helm-chart/kubernetes-dashboard
      helm_options: --set protocolHttp=true --set service.externalPort=9090 --set extraArgs="{--enable-insecure-login=false}" --version=6.0.2 --set serviceAccount.name=kubernetes-dashboard --set rbac.clusterReadOnlyRole=true
      network:
        prefix: /kubernetes-dashboard/
        svcPort: 9090
        addition: '"headers":{"request":{"add":{"x-forwarded-prefix":"/kubernetes-dashboard"}}}'
    prometheus:
      git: https://github.com/prometheus-community/helm-charts.git
      subdir: charts/prometheus
      helm_options: --set prometheus-node-exporter.hostRootFsMount.enabled=false --set server.persistentVolume.volumeName=prometheus-server --set server.securityContext.runAsUser=100100 --set server.securityContext.fsGroup=100100 --set server.prefixURL=/prometheus --set server.baseURL=https://my-lb.adm13/prometheus/
      storage: 
      - name: storage-prometheus-alertmanager-0
        size: 2Gi
      - name: prometheus-server
        size: 8Gi
      network:
        svcName: prometheus-server
        rewrite: /prometheus

