---
applications:
  tools:
    kubernetes-dashboard:
      git: https://github.com/kubernetes/dashboard.git
      platform: arm64
      subdir: charts/helm-chart/kubernetes-dashboard
      helm_options: --set protocolHttp=true --set service.externalPort=9090 --set extraArgs="{--enable-insecure-login=true}" --version=5.7.0 
    kube-state-metrics:
      git: https://github.com/prometheus-community/helm-charts.git
      platform: arm64
      subdir: charts/kube-state-metrics
    prometheus:
      git: https://github.com/prometheus-community/helm-charts.git
      platform: arm64
      subdir: charts/prometheus
