---
applications:
  istio-system:
    base: 
      git: https://github.com/istio/istio.git
      platform: arm
      subdir: manifests/charts/base
    istiod: 
      git: https://github.com/istio/istio.git
      platform: arm
      subdir: manifests/charts/istio-control/istio-discovery
      helm_options: --set global.proxy.privileged=true
  istio-ingress:
    gateway:
      git: https://github.com/istio/istio.git
      subdir: manifests/charts/gateway
      helm_options: --set service.loadBalancerIP="{{ load_balancer_ip }}" --set 'service.externalIPs={"{{ load_balancer_ip }}"}'
  tools:
    infopage:
      git: https://github.com/cainam/k8s_at_home.git
      platform: arm
      subdir: infopage
      storage:
      - name: infopage
        size: 5Mi
      network:
        gwPort: 2000
        targetPort: 12000
        podPort: 80
    kiali:
      git: https://github.com/kiali/helm-charts.git
      subdir: kiali-operator 
      version: v1.60.0
      appVersion: v1.60.0
      helm_options:  --set cr.create=true --set cr.namespace=tools --set cr.spec.istio_namespace=istio-system --set image.tag=v1.60.0 --set allowAdHocKialiImage=true --set cr.spec.deployment.image_name=myregistry.adm13:443/istio/kiali --set cr.spec.deployment.image_version=v1.60.0
    kubernetes-dashboard:
      git: https://github.com/kubernetes/dashboard.git
      subdir: charts/helm-chart/kubernetes-dashboard
      helm_options: --set protocolHttp=true --set service.externalPort=9090 --set extraArgs="{--enable-insecure-login=true}" --version=6.0.2
    prometheus:
      git: https://github.com/prometheus-community/helm-charts.git
      platform: arm
      subdir: charts/prometheus
      xhelm_options: --set nodeExporter.hostRootFsMount.mountPropagation=HostToContainer --set--set nodeExporter.hostRootfs=false --set alertmanager.persistentVolume.volumeName=prometheus-alertmanager --set server.persistentVolume.volumeName=prometheus-server
      helm_options: --set prometheus-node-exporter.hostRootFsMount.enabled=false --set server.persistentVolume.volumeName=prometheus-server --set server.securityContext.runAsUser=100100 --set server.securityContext.fsGroup=100100 
      storage: 
      - name: storage-prometheus-alertmanager-0
        size: 2Gi
      - name: prometheus-server
        size: 8Gi

