---
applications:
  istio-system:
    base: 
      git: https://github.com/istio/istio.git
      branch: 1.19.3
      subdir: manifests/charts/base
    istiod: 
      git: https://github.com/istio/istio.git
      branch: 1.19.3
      subdir: manifests/charts/istio-control/istio-discovery
      helm_options: --set global.proxy.privileged=true --set global.tracing.zipkin.address=jaeger-collector.tools:9411 --set pilot.resources.requests.memory=164Mi 
#      xhelm_options: --set global.proxy.privileged=true --set global.tracing.zipkin.address=jaeger-collector.tools:9411 --set pilot.resources.requests.memory=164Mi {% raw %} {% if applications['istio-system']['istiod']['files']['config']['tempfile'] is defined %}  --values {{ applications['istio-system']['istiod']['files']['config']['tempfile'] }}  {% endif %}  {% endraw %}
      git_to_local_params: --fix_source=.pilot.image=istio/pilot:1.19.3 --fix_source=.global.proxy.image=istio/proxyv2:1.19.3 --fix_source=.global.proxy_init.image=istio/proxyv2:1.19.3
      files:
        values:
          file: istiod-mesh.yaml
    auth-policy:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/auth-policy
      helm_options: --set PolicyName=ext-authz --set hosts[0]="my-lb.adm13"
  auth:
    oauth2-proxy:
      git: https://github.com/oauth2-proxy/manifests.git
      subdir: helm/oauth2-proxy
      helm_options: --set proxyVarsAsSecrets=false 
      ##xhelm_options: --set proxyVarsAsSecrets=false {% raw %} {% if applications['auth']['oauth2-proxy']['files']['config']['tempfile'] is defined %}  --values {{ applications['auth']['oauth2-proxy']['files']['config']['tempfile'] }}  {% endif %}   {% endraw %}
      files:
        values:
          file: oauth2-proxy-config.yaml
      network:
        svcPort: 80
        prefix: /oauth2
    keycloak:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/keycloak
      helm_options: --set securityContext.runAsUser=100200 --set server.securityContext.fsGroup=100200 --set image.tag=22.0.5
      storage:
      - name: keycloak
        size: 1Gi
      network:
        prefix: /
        gateway: kc-gw
        svcPort: 1121
  home:
    common:
      git: https://github.com/k8s-at-home/library-charts.git
      subdir: charts/stable/common
      branch: common-4.5.2
      install: false
    zigbee2mqtt:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/zigbee2mqtt
      affinity: k8s-2-int.adm13
      helm_options: --set zigbee2mqtt.deployment.image.tag=1.35.1 --set zigbee2mqtt.deployment.nodeSelector.zigbee2mqtt=zigbee2mqtt --set persistent.enabled=true --set persistent.capacity=100Mi
      git_to_local_params: --fix_source=.zigbee2mqtt.deployment.image.tag=1.35.1 
      network: yes
      storage:
      - name: zigbee2mqtt
        size: 100Mi
        config: true
    mosquitto:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/mosquitto
      git_to_local_params: --fix_source=.image.tag=2.0.18 --fix_source=.authentication.passwordFilePath=/mosquitto/data/mosquitto.passwd
      storage:
      - name: mosquitto
        size: 1Gi
      network: x
    deconz:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/deconz
      affinity: k8s-2-int.adm13
      #helm_options: --set nodeSelector.deconz=deconz --set securityContext.privileged=true --set env.DECONZ_DEVICE=/dev/ttyAMA0 --set persistence.config.enabled=true --set persistence.config.size=5Mi --set env.DECONZ_VNC_MODE='"0"' --set env.DEBUG_HTTP='"0"' --set env.DEBUG_APS='"1"' --set env.DEBUG_ZCL='"1"' --set env.DEBUG_ZDP='"1"' --set env.DEBUG_DDF='"1"' --set env.DEBUG_DEV='"1"' --set env.DEBUG_OTA='"1"' --set env.DEBUG_ERROR='"1"'
      #helm_options: --set nodeSelector.deconz=deconz --set securityContext.privileged=true --set env.DECONZ_DEVICE=/dev/ttyAMA0 --set persistence.config.enabled=true --set persistence.config.size=5Mi --set env.DECONZ_VNC_MODE='0' --set env.DEBUG_HTTP='0' --set env.DEBUG_APS='1' --set env.DEBUG_ZCL='1' --set env.DEBUG_ZDP='1' --set env.DEBUG_DDF='1' --set env.DEBUG_DEV='1' --set env.DEBUG_OTA='1' --set env.DEBUG_ERROR='1'
      #helm_options: --set nodeSelector.deconz=deconz --set securityContext.privileged=true --set env.DECONZ_DEVICE=/dev/ttyAMA0 --set persistence.config.enabled=true --set persistence.config.size=5Mi --set env.DECONZ_VNC_MODE='\0' --set env.DEBUG_HTTP='\0' --set env.DEBUG_APS='\1' --set env.DEBUG_ZCL='\1' --set env.DEBUG_ZDP='\1' --set env.DEBUG_DDF='\1' --set env.DEBUG_DEV='\1' --set env.DEBUG_OTA='\1' --set env.DEBUG_ERROR='\1'
      helm_options: --set nodeSelector.deconz=deconz --set securityContext.privileged=true --set env.DECONZ_DEVICE=/dev/ttyAMA0 --set persistence.config.enabled=true --set persistence.config.size=5Mi
      git_to_local_params: --fix_source=.image.tag=2.25.0 --fix_source=.env.DECONZ_VNC_MODE=0 --fix_source=.env.DEBUG_HTTP=0 --fix_source=.env.DEBUG_APS=1 --fix_source=.env.DEBUG_ZCL=1 --fix_source=.env.DEBUG_ZDP=1 --fix_source=.env.DEBUG_DDF=1 --fix_source=.env.DEBUG_DEV=1 --fix_source=.env.DEBUG_OTA=1 --fix_source=.env.DEBUG_ERROR=1 --fix_source=.env.DECONZ_VNC_DISABLE_PASSWORD=1
      storage:
      - name: deconz-config
        size: 10Mi
      network:
        svcPort: 80
        prefix: /
        gateway: deconz-gw
    home-assistant:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/home-assistant
      git_to_local_params: --fix_source=.image.tag=2023.11.1 --fix_source=.postgresql.image= 
      remove_dependencies: postgresql,mariadb,influxdb
      cm_helm_options: --set persistence.config.enabled=true --set persistence.config.type=configMap --set persistence.config.name=home-assistant-configuration --set configmap.config.enabled=true
      helm_options: --set persistence.config.enabled=true --set persistence.config.size=100Mi --reset-values
      storage:
      - name: home-assistant-config
        size: 100Mi
        config: true
      network:
        prefix: /
        svcPort: 8123
        gateway: ha-gw
      requires:
          - type: postgresql
            name: postgresql
            namespace: db
            config:
              database: ha
              username: ha
              password: same
  tools:
    jaeger:
      git: https://github.com/jaegertracing/helm-charts.git
      subdir: charts/jaeger
      remove_dependencies: kafka,elasticsearch,cassandra,common
      helm_options: --set provisionDataStore.cassandra=false --set allInOne.enabled=true --set storage.type=none --set agent.enabled=false --set collector.enabled=false --set query.enabled=false --set allInOne.args[0]="--query.base-path=/jaeger"
      network:
        svcName: jaeger-query
        rewrite: /jaeger
        svcPort: 16686
      git_to_local_params: --fix_source=.allInOne.tag=1.45.0 --fix_source=.schema.image= --fix_source=.ingester.image= --fix_source=.agent.image=  --fix_source=.collector.image= --fix_source=.query.oAuthSidecar.image= --fix_source=.query.image= --fix_source=.spark.image= --fix_source=.esIndexCleaner.image= --fix_source=.esRollover.image= --fix_source=.esLookback.image= --fix_source=.hotrod.image.repository=
    infopage:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: charts/infopage
      storage:
      - name: infopage
        size: 5Mi
      network:
        xsvcPort: 1111
    kiali-server:
      git: https://github.com/kiali/helm-charts.git
      subdir: kiali-server
      git_to_local_params: --fix_source=.image.repo=kiali/kiali --fix_source=.image.tag=v1.71.0 --fix_source=.deployment.version_label=v1.71.0 --fix_source=.deployment.image_version=v1.71.0
      network:
        svcPort: 20001
        svcName: kiali
        prefix: /kiali
        rewrite: /kiali
      helm_options: --set auth.strategy=anonymous --set istio_namespace=istio-system
      files:
        values:
          file: kiali-config.yaml
#    kiali-operator:
#      git: https://github.com/kiali/helm-charts.git
#      subdir: kiali-operator 
#      helm_options:  --set cr.create=true --set cr.spec.auth.strategy=anonymous --set cr.namespace=tools --set cr.spec.istio_namespace=istio-system --set allowAdHocKialiImage=true --set cr.spec.deployment.image_name=tools/kiali --set cr.spec.deployment.image_version=v1.68.0 --set cr.spec.external_services.prometheus.url="http://prometheus-server.tools/" --set cr.spec.external_services.prometheus.auth.insecure_skip_verify=true
#      network:
#        svcPort: 20001
#        svcName: kiali
#        prefix: /kiali
#        rewrite: /kiali
#      git_to_local_params: --fix_source=.image.repo=kiali/kiali-operator --fix_source=.image.tag=v1.68.0 --fix_source=.triggerPull.image=kiali/kiali:v1.68.0 
    kubernetes-dashboard:
      git: https://github.com/kubernetes/dashboard.git
      branch: v2.7.0
      xsubdir: charts/helm-chart/kubernetes-dashboard
      subdir: aio/deploy/helm-chart/kubernetes-dashboard
      helm_options: --set protocolHttp=true --set service.externalPort=9090 --set extraArgs="{--enable-insecure-login=false}" --set serviceAccount.name=kubernetes-dashboard --set rbac.clusterReadOnlyRole=true
      remove_dependencies: metrics-server
      network:
        prefix: /kubernetes-dashboard/
        svcPort: 9090
        addition: '"headers":{"request":{"add":{"x-forwarded-prefix":"/kubernetes-dashboard"}}}'
    kube-state-metrics:
      git: https://github.com/prometheus-community/helm-charts.git
      subdir: charts/kube-state-metrics
      xbranch: kube-state-metrics-5.8.2
      branch: prometheus-23.1.0
      git_to_local_params: --fix_source=.image.tag=v2.9.2
      #git_to_local_params: --fix_source=.autosharding.enabled=false
      install: false
    prometheus-node-exporter:
      git: https://github.com/prometheus-community/helm-charts.git
      subdir: charts/prometheus-node-exporter
      xbranch: prometheus-node-exporter-4.18.1
      branch: prometheus-23.1.0
      git_to_local_params: --fix_source=.image.tag=v1.6.1
      install: false
    prometheus-pushgateway:
      git: https://github.com/prometheus-community/helm-charts.git
      subdir: charts/prometheus-pushgateway
      xbranch: prometheus-pushgateway-2.4.0
      branch: prometheus-23.1.0
      git_to_local_params: --fix_source=.image.tag=v1.6.0
      install: false
    prometheus:
      git: https://github.com/prometheus-community/helm-charts.git
      subdir: charts/prometheus
      branch: prometheus-23.1.0
      xhelm_options: --set prometheus-node-exporter.hostRootFsMount.enabled=false --set server.persistentVolume.volumeName=prometheus-server --set server.securityContext.runAsUser=100100 --set server.securityContext.fsGroup=100100 --set server.prefixURL=/prometheus --set server.baseURL=https://my-lb.adm13/prometheus/ --set alertmanager.enabled=false --set kube-state-metrics.autosharding.enabled=false
      helm_options: --set prometheus-node-exporter.hostRootFsMount.enabled=false --set server.persistentVolume.volumeName=prometheus-server --set server.securityContext.runAsUser=100100 --set server.securityContext.fsGroup=100100 --set server.prefixURL=/prometheus --set server.baseURL=https://my-lb.adm13/prometheus/ --set alertmanager.enabled=false
      remove_dependencies: alertmanager
      git_to_local_params: --fix_source=.server.image.tag=v2.45.0
      storage: 
      - name: storage-prometheus-alertmanager-0
        size: 2Gi
      - name: prometheus-server
        size: 8Gi
      network:
        svcName: prometheus-server
        rewrite: /prometheus
  db:
    postgresql:
      #git: https://github.com/cainam/k8s_at_home.git
      git: https://github.com/cetic/helm-postgresql.git
      #subdir: charts/postgresql
      helm_options: --set postgresql.username="{{ service_secrets | selectattr('type', 'match', 'db') | selectattr('name', 'match', 'postgres') | map(attribute='values') | map(attribute='username') | first }}" --set postgresql.password="{{ service_secrets | selectattr('type', 'match', 'db') | selectattr('name', 'match', 'postgres') | map(attribute='values') | map(attribute='password') | first }}"
      git_to_local_params: --fix_source=.image.tag=15.4 --fix_source=.volumePermissions.image.tag=12.2-slim
      storage: 
      - name: data-postgresql-0
        size: 11Gi
      - name: pg-config
        size: 4Mi
  kube-system:
    descheduler:
      git: https://github.com/kubernetes-sigs/descheduler.git
      subdir: charts/descheduler
      xbranch: v0.28.0
      helm_options: --set deschedulerPolicy.strategies.RemoveDuplicates.enabled=false --set deschedulerPolicy.strategies.RemovePodsHavingTooManyRestarts.enabled=false --set deschedulerPolicy.strategies.RemovePodsViolatingNodeTaints.enabled=false --set deschedulerPolicy.strategies.RemovePodsViolatingNodeAffinity.enabled=false --set deschedulerPolicy.strategies.RemovePodsViolatingInterPodAntiAffinity.enabled=false --set deschedulerPolicy.strategies.RemovePodsViolatingTopologySpreadConstraint.enabled=false --set deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.thresholds.cpu=50 --set deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.thresholds.memory=50 --set deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.targetThresholds.cpu=60  --set deschedulerPolicy.strategies.LowNodeUtilization.params.nodeResourceUtilizationThresholds.targetThresholds.memory=50 --set cmdOptions.v=4 --set deschedulerPolicy.evictLocalStoragePods=true --set schedule="@hourly"
