---
applications:
  istio-system:
    base: 
      git: https://github.com/istio/istio.git
      platform: arm
      subdir: manifests/charts/base
    istiod: 
      git: https://github.com/istio/istio.git
      platform: arm
      subdir: manifests/charts/istio-control/istio-discovery
      helm_options: --set global.proxy.privileged=true --set global.hub="{{ my_registry }}/istio" --set global.tag=1.16.0
  istio-ingress:
    gateway:
      git: https://github.com/istio/istio.git
      subdir: manifests/charts/gateway
      helm_options: --set 'service.externalIPs={"{{ load_balancer_ip }}"}' 
      xhelm_options: --set 'service.loadBalancerIP="{{ load_balancer_ip }}"' --set 'service.externalIPs={"{{ load_balancer_ip }}"}'
  auth:
    oauth2-proxy:
      git: https://github.com/oauth2-proxy/manifests.git
      subdir: helm/oauth2-proxy
      helm_options: --set proxyVarsAsSecrets=false
      network:
        gwPort: 2004
        targetPort: 12004
        svcPort: 80
    keycloak:
      git: https://github.com/cainam/k8s_at_home.git
      subdir: keycloak
      helm_options: --set securityContext.runAsUser=100200 --set server.securityContext.fsGroup=100200
      storage:
      - name: keycloak
        size: 1Gi
      network:
        gwPort: 2005
        targetPort: 12005
        svcPort: 1121
  tools:
    infopage:
      git: https://github.com/cainam/k8s_at_home.git
      platformX: arm
      subdir: infopage
      storage:
      - name: infopage
        size: 5Mi
      network:
        gwPort: 2000
        targetPort: 12000
        svcPort: 1111
    kiali-operator:
      git: https://github.com/kiali/helm-charts.git
      subdir: kiali-operator 
      chart_version: v1.62.0
      appVersion: v1.62.0
      helm_options:  --set cr.create=true --set cr.namespace=tools --set cr.spec.istio_namespace=istio-system --set image.repo=myregistry.adm13:443/tools/kiali-operator --set image.tag=v1.62.0 --set allowAdHocKialiImage=true --set cr.spec.deployment.image_name=myregistry.adm13:443/tools/kiali --set cr.spec.deployment.image_version=v1.62.0 --set cr.spec.external_services.prometheus.url="http://prometheus-server.tools/" --set cr.spec.external_services.prometheus.auth.insecure_skip_verify=true
      network:
        gwPort: 2002
        targetPort: 12002
        svcPort: 20001
        service: kiali
    kubernetes-dashboard:
      git: https://github.com/kubernetes/dashboard.git
      subdir: charts/helm-chart/kubernetes-dashboard
      helm_options: --set protocolHttp=true --set service.externalPort=9090 --set extraArgs="{--enable-insecure-login=true}" --version=6.0.2
      network:
        gwPort: 2001
        targetPort: 12001
        svcPort: 9090
    prometheus:
      git: https://github.com/prometheus-community/helm-charts.git
      platformX: arm
      subdir: charts/prometheus
      xhelm_options: --set nodeExporter.hostRootFsMount.mountPropagation=HostToContainer --set--set nodeExporter.hostRootfs=false --set alertmanager.persistentVolume.volumeName=prometheus-alertmanager --set server.persistentVolume.volumeName=prometheus-server
      helm_options: --set prometheus-node-exporter.hostRootFsMount.enabled=false --set server.persistentVolume.volumeName=prometheus-server --set server.securityContext.runAsUser=100100 --set server.securityContext.fsGroup=100100 
      storage: 
      - name: storage-prometheus-alertmanager-0
        size: 2Gi
      - name: prometheus-server
        size: 8Gi

