external_services:
  prometheus:
    url: http://prometheus-server.tools/prometheus
    auth:
      insecure_skip_verify: true
  tracing:
    in_cluster_url: http://jaeger-query.tools:16685/jaeger
    enabled: true
    url: https://{{ base_domain }}/jaeger
  istio:
    root_namespace: istio-system
    component_status:
      enabled: true
      components:
      - app_label: istiod
        is_core: true
      - app_label: gateway
        is_core: true
        is_proxy: true
        namespace: istio-ingress
