---

- name: assert | Test ca_requests
  ansible.builtin.assert:
    that:
      - ca_requests is iterable
    quiet: true
  when:
    - ca_requests is defined

- name: assert | Test item of ca_requests
  ansible.builtin.assert:
    that:
      - item is string or
        item is iterable
      - item is not none
    quiet: true
  loop: "{{ ca_requests }}"
  when:
    - ca_requests is defined
    - item.name is defined

- name: assert | Test variables defined?, string?, not none?
  ansible.builtin.assert:
    that:
    - ca_openssl_path is defined and ca_openssl_path is string and ca_openssl_path is not none
    - ca_private_path is defined and ca_private_path is string and ca_private_path is not none
    - ca_certs_path is defined and ca_certs_path is string and ca_certs_path is not none
    - ca_privatekey_path is defined and ca_privatekey_path is string and ca_privatekey_path is not none
    - ca_csr_path is defined and ca_csr_path is string and ca_csr_path is not none
    - ca_certificate_path is defined and ca_certificate_path is string and ca_certificate_path is not none
    - certificates_configuration is defined and certificates_configuration is mapping
    - certificates_configuration.ca_common_name is defined and certificates_configuration.ca_common_name is string and (certificates_configuration.ca_common_name|length > 0)
    - certificates_configuration.ca_passphrase is defined and certificates_configuration.ca_passphrase is string and certificates_configuration.ca_passphrase is not none
    quiet: true
