# handles certificate management
# input parameter:
# - cert_results_var => keys and certs of the requested certificates
# - caBundle_var

- name: assert
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: set path for CA
  ansible.builtin.set_fact:
    ca_path:      "{{ certificates_configuration.ca_openssl_path }}/{{ certificates_configuration.ca_common_name }}"
    ca_root_path: "{{ certificates_configuration.ca_openssl_path }}/{{ certificates_configuration.ca_common_name }}/rootCA"

- name: Generate ca certificates
  ansible.builtin.include_tasks:
    file: generate_ca_certs.yml
  when: ca_init and ca_own_root

- block:
  - name: main | read CA certificates
    ansible.builtin.slurp:
      src: "{{ ca_root_path }}/{{ item.path }}"
    loop:
      - "{{ ca_root_certificate_path }}"
      - "{{ ca_certificate_path }}"
    register: _cacerts

  - name: main | save caBundle var
    set_fact:
      "{{ caBundle_var }}": "{{ (_cacert.results[0].content | b64decode ~ _cacert.results[1].content | b64decode) | b64encode }}"
  when: caBundle_var is defined

- name: main | Create ca chain
  ansible.builtin.copy:
    content: "{{ _cacert.content| b64decode }}{{ _cacert_root.content| b64decode }}"
    dest: "{{ ca_path }}/{{ ca_certificate_path }}"
    mode: "0644"
  when: ca_init and ca_own_root

- name: Handle requests
  vars: 
    ca_root_path: "{{ ca_path }}/rootCA"
  ansible.builtin.include_tasks:
    file: requests.yml
  loop: "{{ ca_requests }}"
  loop_control:
    loop_var: request
    label: "{{ request.name | default(request) }}"
  when:
    - ca_requests is defined
