- name: gluster peering
  gluster_peer:
    state: present
    nodes:
      - "{{ item }}"
  loop: "{{ gluster_hosts }}"

- name: set app name
  set_fact:
    app: registry

- name: app:{{ app }} storage bricks
  include_tasks: common/storage_brick.yml
  vars:
    outside_k8s: true
  with_items:
    - name: registry
      size: 5G
  loop_control:
    loop_var: storage

- name: app:{{ app }} storage
  include_tasks: common/storage.yml
  vars:
    outside_k8s: true
  with_items:
    - name: registry
  loop_control:
    loop_var: storage
  run_once: true


