---
- name: gentoo files
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}/{{ item.file }}"
    mode: 0644
    backup: yes
  loop:
    - file: world
      dest: /var/lib/portage
    - file: gentoo.conf
      dest: /etc/portage/repos.conf
      
- name: make.conf
  template:
    src: make.conf
    dest: "/etc/portage/make.conf"
    backup: yes 
