homeassistant: true
permit_join: true
frontend:
  port: 8080
  host: 0.0.0.0
  url: https://open.my-lb.adm13/
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto.home:1883
  user: x
  password: x
serial:
  port: /dev/ttyUSB0
  adapter: deconz
  baudrate: 115200
advanced:
  adapter_delay: 200
  last_seen: ISO_8601
  legacy_availability_payload: false
  legacy_api: false
  timestamp_format: 'YYYY-MM-DD HH:mm:ss'
  log_directory: /app/%TIMESTAMP%
  log_level: info
  log_rotation: true
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 15
availability:
  active:
    timeout: 10
  passive:
    timeout: 30
device_options:
  legacy: false
  homeassistant:
    last_seen:
      enabled_by_default: true
devices:
  '0x7cb94c76e5d50000':
    friendly_name: Warmwasserpumpe
  '0x842e14fffef15323':
    friendly_name: Werkstatt
  '0x94deb8fffe41e447':
    friendly_name: Wegbeleuchtung
  '0x00158d0007bde782':
    friendly_name: Temperatur
  '0xa4c1384521e152f5':
    friendly_name: Pool
  '0xa4c1383fcaf256b0':
    friendly_name: Terrasse
  '0xa4c138d122942108':
    friendly_name: Telefon
  '0xf0d1b8be24084e34':
    friendly_name: Lyra
  '0xa4c138e2bc190354':
    friendly_name: Carport
