homeassistant: true
permit_join: true
frontend:
  port: 8080
  host: 0.0.0.0
  url: https://open.my-lb.adm13/
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto.home:1883
  user: x
  password: x
serial:
  port: /dev/ttyUSB0
  adapter: deconz
  baudrate: 115200
advanced:
  adapter_delay: 350
  log_level: debug
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 20
devices:
  '0x00158d0007bde782':
    friendly_name: Temperatur
    icon: >-
      data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QCMRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAJagAwAEAAAAAQAAAJYAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/bAEMACQYHEA8NDw0NEA0NDw8NDQ4ODQ0NDw4NDQ0VERYWFRETFRgdKCAYGiUbFRUhMSElKSsuLi4XHzM4Myw3KC0uK//bAEMBCgoKDQ0NDg0NDisZFRkrNys3Kys3Kzc3Ky0rNysrKysrKysrKysrLS0rKysrLSstKy0tKysrKystKysrKysrK//AABEIAJYAlgMBIgACEQEDEQH/xAAaAAEAAwEBAQAAAAAAAAAAAAAAAQIDBAUH/8QALBAAAgICAAYBAwQCAwAAAAAAAAECEQMhBBIxQVFhcRMigTKRobEUQsHh8f/EABYBAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8A+4gAAAAAAAAgASCABIIAEggkAAAAAAAAAAAABAAWCmSSS2BbmM5ZkjCeW/RQ1Bs877E/XfowAg6YZ130aKSfR2cbEXXQkHcDmhmfc3hNPoILggEEggkAAAAAAgMNmOTL4GC051s5pTb2/wDwhyb6kGoIRIBQFgALACYEhPegQyDaGfz0N4yvaOJEqXgQdyJOaGfybxd9DIsAABVsNnLly3pFwXyZuxgwSUQwSCiAAQCG62UllS779GcZpu5O/C/1T90BfmfWkkl3dWi+OVpNfBgoOe5fpXRJHQklpdOwEgAAAABbDPlfoqiGB3c2rBXFuKvwDInI6izjOzKvtZy1ouCpIIbKAAQBmOdbjfRt9DaTpNvS7sjTWt6tX4A45ymrpOl05Vr5s1ww+6KrXLtLa5vLNfpL3+5Kj+P7Aty1q79kE2AAAAAAAismWspIDt4V3BP5BThH9i+WDI2yLTOddDplvXycsGnpPpplwJRM2jYh1/2UZAvVp1TrVla+AKsJAkAAAAAACwRZRJDFlXsBZTLkXZW+iX/JGTJWkrb7ezfguGdqc9yr9iDpwY3GCjfyDVIGQOTiMNPmR2UQ1ZcHDDL50b+1TWq+RmwKXY5pQlBp1avzso5s0+WTe8UnL9W5Y5P34OrDmcvtnGpVacdxZhki7bg+W+sJK4zJ4OSU0qljpO4PcfwyjpcCtGqQaIMmRZo4EfSAqgW+myXEChVlpFGyhZjly7qO32SIyZG3yRVtnbwnCKKuW5f0TRThOFr7p7k+jO6KJSJJQABAAAEFZRssAOXLwqfn5MHFx7cy7vukeiyrgu5aOWGZPV/guRk4ZdUZrmj12ijYGayryXT9oCSkyzdGWTPFdSismc05uf2Q/L8GihLI6ScY/wAs7sGBRWlRNGfC8Kory/J10QSmZEgAAAAAAAAAAAAIZVxLADDJw6foyfCeH/J2UKLRx/4jfVsvj4VL38nTQoUViqLCgQCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/Z
  '0x7cb94c76e5d50000':
    friendly_name: Warmwasserpumpe
    state_action: false
  '0x70b3d52b60076b69':
    friendly_name: '0x70b3d52b60076b69'
availability: true
