---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
data:
  request.json: |-
      {
        "client_id": "{{ .Values.config.client_id }}",
        "client_name": "{{ .Values.config.client_name }}",
        "client_secret": "{{ .Values.config.client_secret }}",
        "grant_types": {{ .Values.config.grant_types | toJson}},
        "redirect_uris": {{ .Values.config.redirect_uris | toJson }},
        "response_types": {{ .Values.config.response_types | toJson }},
        "scope": "{{ .Values.config.scope }}",
        "token_endpoint_auth_method": "{{ .Values.config.token_endpoint_auth_method }}"
      }

  client_id.sh: |-
    #!/bin/bash
    curl -f -L -X GET 'http://hydra-admin.auth:4445/clients/{{ .Values.config.client_id }}'  -H 'Content-Type: application/json' 
    if [ $? -ne 0 ]; then
      curl -v -L -X POST 'http://hydra-admin.auth:4445/clients' -H 'Content-Type: application/json'  --data-raw "$(cat /request.json)"
    else
      echo "client_id is already configured"
    fi
    #sleep 1800

