apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.operator.name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: auth
  template:
    metadata:
      labels:
        application: auth
    spec:
      serviceAccountName: {{ include "operator.serviceAccountName" . }}
      volumes:
      - name: "{{ .Values.operator.name }}"
        persistentVolumeClaim:
          claimName: "{{ .Values.operator.name }}"
      containers:
      - name: "{{ .Values.operator.name }}"
        image: "{{ .Values.operator.image }}:{{ .Values.operator.tag }}"
        command: 
        - kopf
        args:
        - run
        - -n
        - {{ .Release.Namespace }}
        - /app/kopf.py
        env:
        - name: REDIRECT_URL
          value: {{ .Values.redirect_url }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: OAUTH2_CONFIG_SECRET
          value: "oauth2-proxy-alpha"
        - name: OAUTH2_SECRET_FILE
          value: 'oauth2_proxy.yml'
        - name: HYDRA_SERVICE
          value: "hydra-admin"
        - name: HYDRA_SERVICE_PORT
          value: "4445"
        - name: HYDRA_SEARCH_LABEL_KEY
          value: 'app.kubernetes.io/instance'
        - name: HYDRA_SEARCH_LABEL_VALUE
          value: 'hydra'
        volumeMounts:
        - mountPath: /app
          name: "{{ .Values.operator.name }}"

