apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.operator.name | quote }}
  labels:
    app: {{ .Values.operator.name | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.operator.volumeSize | quote }}
