{{- if .Values.persistent.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra-shared
  labels:
    app: hydra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent.capacity | quote }}
{{- end }}
