kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["services","virtualservices"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["list"]

