---

a2:
  ns1:
    1a1:
      requires:
      - name: 3a5
        namespace: ns2
      - name: 2a4
        namespace: ns2
      v: m
      network: 
        gateway: open
    1a2:
      git: tor2.git
      requires:
      - name: 1a3
        namespace: ns1
    1a3:
      v: v
      requires:
      - name: 2a4
        namespace: ns2
  ns2:
    2a4:
      v: o
      requires:
      - name: 1a2
        namespace: ns1
  ns3:
    3a5:
      e: e
    3a6:
      f: f
      network: true
  

