- name: set namespace fact
  set_fact:
    ns: "{{ namespace.key }}"
  
- name: "namespace: {{ ns }} - manage applications"
  include_tasks: manage_one_application.yml
  loop: "{{ namespace.value | dict2items }}"
  loop_control:
    loop_var: application
