- name: set namespace fact
  set_fact:
    ns: "{{ namespace.key }}"
  
- name: manage application in {{ ns }}
  include_tasks: manage_one_application.yml
  when: (limit_application is not defined or application.key == limit_application) 
  loop: "{{ namespace.value | dict2items }}"
  loop_control:
    loop_var: application
