- name: configure namespace
  shell: |
    kubectl create namespace "{{ namespace.key }}"
    echo "{{ namespace.key }}" | grep -q -e kube -e istio || kubectl label namespace "{{ namespace.key }}" istio-injection=enabled
  register: out

# The error was: ModuleNotFoundError: No module named 'kubernetes'
#- name: Create a k8s namespace
#  kubernetes.core.k8s:
#    kubeconfig: /etc/kubernetes/admin.conf
#    name: testing
#    api_version: v1
#    kind: Namespace
#    state: present
      
- name: set namespace fact
  set_fact:
    ns: "{{ namespace.key }}"
  
- name: manage application in {{ ns }}
  include_tasks: manage_one_application.yml
  loop: "{{ namespace.value | dict2items }}"
  loop_control:
    loop_var: application
