- name: set app fact
  set_fact:
    ns: "{{ namespace.key }}"

- block:
  - name: namespace:{{ ns }} - configure namespaces to enable istio-injection
    shell: |
      kubectl apply -f - <<EOF
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ namespace.key }}
      EOF
      echo "{{ namespace.key }}" | grep -q -e kube -e istio-system || kubectl label namespace "{{ namespace.key }}" istio-injection=enabled
    register: namespace_out
  
  - name: namespace:{{ ns }} namespace management output
    debug:
      msg: "output: item: {{ item }}"
    loop: "{{ namespace_out  | dict2items }}"

-   

- name: prepare by application
  include_tasks: prepare_application.yml
  loop: "{{ namespace.value | dict2items }}"
  loop_control:
    loop_var: application

