- name: set app fact
  set_fact:
    app: "{{ application.key }}"

- block:
  - name: app:{{ app }} storage
    include_tasks: common/storage_brick.yml
    when: application.value.storage is defined #|| storage is defined
    with_items: "{{ application.value.storage }}"
    loop_control:
      loop_var: storage
  when: application.value.storage is defined

