- set_fact:
    app_cfg_templates_path: "{{ role_path }}/templates/{{ storage.name }}"
    app_cfg_files_path: "{{ role_path }}/files/{{ storage.name}}"
    dest_base_dir: "{% if storage.type == 'local_folder' %}{{ local_disk_directory }}{% else %}{{ shared_mounts }}{% endif %}/{{ storage.name }}"

- name: set directories
  set_fact:
    templates_dirs: "{{  lookup('pipe', '[ ! -d \"'+ app_cfg_templates_path +'\" ] || find \"'+ app_cfg_templates_path +'\" -type d').split('\n')|reject('match', '^$')  }}"
    files_dirs: "{{      lookup('pipe', '[ ! -d \"'+ app_cfg_files_path     +'\" ] || find \"'+ app_cfg_files_path     +'\" -type d').split('\n')|reject('match', '^$')  }}"
    templates_files: "{{ lookup('pipe', '[ ! -d \"'+ app_cfg_templates_path +'\" ] || find \"'+ app_cfg_templates_path +'\" ! -type d').split('\n')|reject('match', '^$')  }}"
    files_files: "{{     lookup('pipe', '[ ! -d \"'+ app_cfg_files_path     +'\" ] || find \"'+ app_cfg_files_path     +'\" ! -type d').split('\n')|reject('match', '^$')  }}"
#    list_templates: "{{ lookup('pipe', '[ ! -d \"'+ app_cfg_templates_path +'\" ] || find \"'+ app_cfg_templates_path +'\" -type d', wantlist=True)|reject('match', '^$')  }}"
#    list_files: "{{ lookup('pipe', '[ ! -d \"'+ app_cfg_files_path +'\" ] || find \"'+ app_cfg_files_path +'\" -type d', wantlist=True)|reject('match', '^$')  }}"

- name: determine destination hosts
  set_fact:
    dest: "{% if storage.type == 'local_folder' %}{{ hostvars.keys() }}{% else %}{{ [hostvars.keys() | first] }}{% endif %}"
  run_once: true

- name: list destination hosts
  debug:
    msg: "destination hosts:\n{{ dest }}"
  run_once: true

- block:
  - debug: var=inventory_hostname
  - name: ensure destination directory exists for templates
    file:
      path: "{{ dest_base_dir }}{{ item | replace (app_cfg_templates_path,'') }}"
      recurse: true
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    loop: "{{ templates_dirs }}"

  - name: ensure destination directory exists for files
    file:
      path: "{{ dest_base_dir }}{{ item | replace (app_cfg_files_path,'') }}"
      recurse: true
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    loop: "{{ files_dirs }}"

  - name: dbg files_dirs
    debug:
      msg: "loop var: {{ item }} app_cfg_files_path: {{ app_cfg_files_path }} dest: {{ dest_base_dir }}/{{ item | replace( app_cfg_files_path , '') }} count: {{ files_dirs| length}}"
    loop: "{{ files_dirs }}"
    when: "'debug' in ansible_run_tags"

  - name: dbg templates_dirs
    debug:
      msg: "loop var: -{{ item }}- app_cfg_templates_path: {{ app_cfg_templates_path }} dest: {{ dest_base_dir }}/{{ item | replace( app_cfg_templates_path , '') }} count: {{ templates_dirs| length}}"
    loop: "{{ templates_dirs }}"
    when: "'debug' in ansible_run_tags"

  - name: create config from templates
    template:
      src: "{{ item }}"
      dest: "{{ dest_base_dir }}/{{ item | replace( app_cfg_templates_path , '') }}"
    loop: "{{ templates_files }}"

  - name: create config from files
    copy:
      src: "{{ item }}"
      dest: "{{ dest_base_dir }}/{{ item | replace( app_cfg_files_path , '') }}"
    loop: "{{ files_files }}"
  
  when: "inventory_hostname in dest"
#  run_once: true

- name: Example using fail and when together
  ansible.builtin.fail:
    msg: let's stop here
  when: false
