#!/bin/bash

action=$1
atype=$2
search=$3
add=$4

if (echo "$action" | grep -q ^d); then 
  action=describe
elif (echo "$action" | grep -q ^g); then
  action="get -o yaml"
elif (echo "$action" | grep -q ^e); then
  action="exec -it "
  add="-- $3"
  search=$2
  [ "$add" == "" ] && add="-- bash"
  atype=pod
elif (echo "$action" | grep -q ^l); then
  action=logs
  atype=pod
  search=$2
fi

case "$atype" in
  s)
    atype="svc"
  ;;
  p)
    atype="pod"
  ;;
  d)
    atype="deploy"
  ;;
esac

read i n < <(
for label in app.kubernetes.io/instance app app.kubernetes.io/name; do
kubectl get $atype -A -l $label=$search --no-headers=true  -o jsonpath="{..metadata.name} {..metadata.namespace}" | grep -v "^ $" 
done
)

if (echo $action | grep -q -e ^exec -e ^logs); then
  atype=
fi
echo "namespace: $n item: $i"
kubectl $action $atype -n $n $i $add

