apiVersion: v1
kind: Service
metadata:
  name: {{ include "infopage.fullname" . }}
  labels:
    {{- include "infopage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Chart.Name }}
      protocol: TCP
      name: http
  selector:
    {{- include "infopage.selectorLabels" . | nindent 4 }}
