
# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 127.0.0.6
    - ::1
    - 10.104.248.34
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

recorder:
    auto_purge: false
    purge_keep_days: 4000
    db_url: postgresql://ha:same@postgresql.db.svc.cluster.local/ha
    #db_url: !secret psql_string
    db_retry_wait: 15

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
