---
# file: site.yml
- hosts: all
  gather_facts: yes
  vars:
    auto_legacy_silent: true
    auto_silent: true
    ansible_python_interpreter: /usr/bin/python # to avoid interpreter warning
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - role: k8s-base
      tags: 
        - never
        - k8s
    - role: gentoo
      tags: 
        - never
        - gentoo
