---
# file: site.yml
- hosts: all
  gather_facts: yes
  any_errors_fatal: true
  vars:
    auto_legacy_silent: true
    auto_silent: true
    ansible_python_interpreter: /usr/bin/python # to avoid interpreter warning
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    PATH: "/usr/local/bin/:/usr/sbin:/usr/bin:/sbin:/bin" 
    registry: "{{ registry }}"
  pre_tasks:
  - name: include software
    include_vars: vars/software
    tags:
    - image-build
    - deploy
    - k8s
    - gentoo
    - testing

  roles:
    - role: always
      tags:
        - always
    - role: image-build
      tags:
        - never
        - image-build
    - role: k8s
      tags: 
        - never
        - k8s
    - role: gentoo
      tags: 
        - never
        - gentoo
    - role: deploy
      tags:
        - never
        - deploy
    - role: raspberry
      tags:
        - never
        - raspberry
    - role: testing
      tags:
        - never
        - testing

