- name: set app fact
  set_fact:
    app: "{{ application.key }}"

- block:
  - name: print application.value {{ app }}
    debug:
      msg: "{{ application.value }}"
      
  - name: app:{{ app }} helm_options
    debug:
      msg: "xx:{{ port.name }} index:{{ port_idx }}"
    loop: "{{ application.value.ports }}"
    loop_control:
      loop_var: port
      index_var: port_idx

  - name: combine gateway deployment into applications # all raw items have to be treated before!
    set_fact: 
      applications: "{{ applications | combine(
         {namespace.key : 
           {application.key: 
              {'helm_options': (applications[namespace.key][application.key].helm_options | default('--set name='~application.key))~' --set service.ports['~port_idx~'].name='~port.name~',service.ports['~port_idx~'].port='~port.port~',service.ports['~port_idx~'].protocol='~port.protocol~',service.ports['~port_idx~'].targetPort='~port.targetPort~' ' } 
          }}, recursive=true)}}"
    loop: "{{ application.value.ports }}"
    loop_control:
      loop_var: port
      index_var: port_idx
  when: application.value.type is defined and application.value.type=='gateway'
