---
- name: test
  gather_facts: false
  hosts: all
  vars:
    k8s_check_file: /tmp/kh

  tasks:
  - block:
    - set_fact:
        gateway: "ha-gw"
    - debug: 
        msg: "{{ gateways[gateway].hosts }}"
    - debug: 
        msg: "{{ gateways[gateway].hosts | to_yaml}}"
    - name: format
      shell: | 
        echo -e "apiVersion: networking.istio.io/v1beta1\nkind: Gateway\nmetadata:\n  name: name\n  namespace: namespace\nspec:\n  selector:\n    istio: gateway\n  servers:\n  - hosts:\n    {{ gateways[gateway].hosts | to_nice_yaml(indent=4) }}\n    port:\n      name: https\n      number: 443\n      protocol: HTTPS\n    tls:\n      credentialName: gateway\n      mode: SIMPLE"
        echo -e "apiVersion: networking.istio.io/v1beta1\nkind: Gateway\nmetadata:\n  name: name\n  namespace: namespace\nspec:\n  selector:\n    istio: gateway\n  servers:\n  - hosts:\n    {{ gateways[gateway].hosts | to_nice_yaml(indent=4) | trim | indent(4)}}\n    port:\n      name: https\n      number: 443\n      protocol: HTTPS\n    tls:\n      credentialName: gateway\n      mode: SIMPLE"
      register: out
    - debug:
        msg: "{{ out.stdout }}"
    run_once: true
