---

- name: test 
  gather_facts: false
  hosts: all
  tasks:
  - set_fact:
        ns: tools
        gluster_ips:
          - eins
          - zwei

  - shell: |
         echo "{% for i in gateways %}
            {{ gateways[i].external_ip }} {{ gateways[i].domain }}
           {% endfor %}"
    register: y
  - debug: var=y
           ## {{ i.value.external_ip }} {{ i.value.domain }}

