---
- name: test
  gather_facts: false
  hosts: all
  vars:
    k8s_check_file: /tmp/kh

  tasks:
  - name: include secrets (wlan, ssh_host_keys)
    include_vars: "{{ local_only }}/secrets"

  - name: create file content from variables directly without template
    copy:
      content: |
        {% for a in ssh_host_keys %}
        {{ a }}
        {% endfor %}
      dest: /tmp/skh

