---
- name: test
  gather_facts: false
  hosts: all
  tasks:
    - name: set namespace fact
      set_fact:
        ns: "istio-system"
     
    - name: debug indention
      debug:
        msg: |
          {{ local_ca | indent( width=12, first=True) }}


    - name: manage application in {{ ns }}
      debug: 
        msg: "msg"
      #when: limit_namespace is not defined or {{ ns }} == limit_namespace
      when: limit_namespace is not defined or ns == limit_namespace

