namespace: {{ kustom.namespace }}

resources:
- CronJob.yaml
- RoleBinding.yaml
- Role.yaml
- ServiceAccount.yaml

configMapGenerator:
- name: {{ kustom.name }}
  literals: []

generatorOptions:
  disableNameSuffixHash: true
