kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: "myregistry.adm13:443/k8s"
controlPlaneEndpoint: "k8s.adm13:7443"
networking:
 podSubnet: "10.244.0.0/16"
kubernetesVersion: {{ k8s_version }}
