kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
localAPIEndpoint:
  advertiseAddress: {{ internal_first_master_ip }}

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: "myregistry.adm13:443/k8s"
controlPlaneEndpoint: "k8s.adm13:7443"
networking:
 podSubnet: "10.244.0.0/16"
kubernetesVersion: v1.25.2
---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
localAPIEndpoint:
  advertiseAddress: {{ internal_secondary_master_ip | default("") }}
etcd:
    local:
        extraArgs:
          listen-peer-urls: https://{{ internal_secondary_master_ip | default("") }}:2380
          listen-client-urls: https://{{ internal_secondary_master_ip | default("") }}:2379
          initial-advertise-peer-urls: https://{{ inventory_hostname }}:2380
          advertise-client-urls: https://{{ inventory_hostname }}:2379
