apiVersion: v1
items:
- apiVersion: security.istio.io/v1
  kind: AuthorizationPolicy
  metadata:
    name: ext-authz2
    namespace: tools
  spec:
    action: CUSTOM
    provider:
      name: oauth2-proxy
    rules:
    - to:
      - operation:
          hosts:
          - my-lb.adm13
    selector:
      matchLabels:
        istio: gateway
kind: List
