- name: get list of images
  shell: kubeadm config images list --kubernetes-version "{{ k8s_version }}" 2>/dev/null
  register: required_images
  changed_when: false

- debug:
    msg: "images to download: {{ required_images.stdout_lines }}"

- name: handle additional images
  vars:
    limit_images:
    - helm
    - registry
  import_tasks: common/images.yaml
  # failed_when: true
  
- name: pull, tag and push k8s images
  shell: |
    echo "arm64 {{ item }} /k8s/ # required for kubernetes" | bash pull-tag-push.sh
  with_items: "{{ required_images.stdout_lines }}"

- name: prepare flannel
  shell: |
    . set_env.sh kube-flannel
    helm:from_git_to_local.sh --platform="{{ item.platform | default(default_platform) }}" --git_source=https://github.com/flannel-io/flannel.git
    helm repo add kube-flannel "{{ helm_repo_base }}kube-flannel"
    helm repo index "${helm_repo_dir}" --url "{{ helm_repo_base }}kube-flannel"


