apiVersion: kubeadm.k8s.io/v1beta4
kind: UpgradeConfiguration
timeouts:
  upgradeManifests: 15m
UpgradeApplyConfiguration:
  etcdUpgrade: true
apply:
  patches:
    directory: /etc/kubernetes/patches
node:
  patches:
    directory: /etc/kubernetes/patches
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: "{{ software.kubernetes.version|string }}"
etcd:
  local:
    imageRepository: myregistry.adm13:443/k8s
    imageTag: {{ software.etcd.version }}

